// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkg-Z4-PQDBK2H0VTmIV5oUKtsTua81-8',
    appId: '1:533098012536:web:04c8e94a2eaf48e677f28d',
    messagingSenderId: '533098012536',
    projectId: 'fyp2-13174',
    authDomain: 'fyp2-13174.firebaseapp.com',
    storageBucket: 'fyp2-13174.firebasestorage.app',
    measurementId: 'G-Y9SXYG955J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqcTbgKIk5FDTiSG5FSsOBgshH4S0aw2g',
    appId: '1:533098012536:android:328c86a6a3c0052377f28d',
    messagingSenderId: '533098012536',
    projectId: 'fyp2-13174',
    storageBucket: 'fyp2-13174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2DpR7owPNKeWlHCPIOhhjTt4fDNuCJ-c',
    appId: '1:533098012536:ios:84b142bd8ac5fd4e77f28d',
    messagingSenderId: '533098012536',
    projectId: 'fyp2-13174',
    storageBucket: 'fyp2-13174.firebasestorage.app',
    iosBundleId: 'com.example.fyp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2DpR7owPNKeWlHCPIOhhjTt4fDNuCJ-c',
    appId: '1:533098012536:ios:84b142bd8ac5fd4e77f28d',
    messagingSenderId: '533098012536',
    projectId: 'fyp2-13174',
    storageBucket: 'fyp2-13174.firebasestorage.app',
    iosBundleId: 'com.example.fyp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkg-Z4-PQDBK2H0VTmIV5oUKtsTua81-8',
    appId: '1:533098012536:web:a9fa1e5ffc65c86477f28d',
    messagingSenderId: '533098012536',
    projectId: 'fyp2-13174',
    authDomain: 'fyp2-13174.firebaseapp.com',
    storageBucket: 'fyp2-13174.firebasestorage.app',
    measurementId: 'G-PNZQXLXCKB',
  );

}